title: Karim Said
author: Karim Said
email: karim@egyptiankarim.com
description: Karim Said's website.

baseurl: ""
url: "https://egyptiankarim.com"

instagram_url: "https://instagram.com/egyptiankarim"
twitter_url: "https://twitter.com/egyptiankarim"
github_url:  "https://github.com/egyptiankarim"
medium_url: "https://medium.com/@egyptiankarim"
linkedin_url: "https://www.linkedin.com/in/egyptiankarim"
keybase_url: "https://keybase.io/egyptiankarim"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

collections:
  projects:
    output: true

exclude: ['Gemfile', 'Gemfile.lock']
