title: Karim A Said
author: Karim A Said
email: karim@egyptiankarim.com
description: Karim Said's website.

baseurl: ""
url: "https://egyptiankarim.com"

gravatar_url: "https://en.gravatar.com/userimage/2909251/a417dc892218069a66303458efd49d17.jpg?size=500"

instagram_url: "https://instagram.com/egyptiankarim"
twitter_url: "https://twitter.com/egyptiankarim"
github_url:  "https://github.com/egyptiankarim"
medium_url: "https://medium.com/@egyptiankarim"
linkedin_url: "https://www.linkedin.com/in/egyptiankarim"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

collections:
  projects:
    output: true

exclude: ['Gemfile', 'Gemfile.lock']
